#!/usr/bin/env bash


BASE_CONFIG_PATH=~/.config
NVIM_PATH=$BASE_CONFIG_PATH/nvim
cp -r nvim $BASE_CONFIG_PATH


# Install Vim-Plug
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim


nvim +PlugInstall +qall
nvim +PlugInstall +qall

sudo pip install flake8


# Configure Flake8
cp flake8.config ~/.config/


if [ -x "$(command -v go)" ]
then
    nvim -c ':GoInstallBinaries'
fi


